// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ordering_cart.Migrations
{
    [DbContext(typeof(CartDb))]
    [Migration("20250111222829_migration3")]
    partial class migration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Cart", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<float?>("count")
                        .HasColumnType("float");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("cart");
                });

            modelBuilder.Entity("ProductDto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("amount")
                        .HasColumnType("int");

                    b.Property<float?>("count")
                        .HasColumnType("float");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<int>("idCart")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<float?>("price")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("idCart");

                    b.ToTable("products");
                });

            modelBuilder.Entity("ProductDto", b =>
                {
                    b.HasOne("Cart", "cart")
                        .WithMany("listProducts")
                        .HasForeignKey("idCart")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cart");
                });

            modelBuilder.Entity("Cart", b =>
                {
                    b.Navigation("listProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
